export const BOOKS_LOAD_REQUEST = "BOOKS_LOAD_REQUEST";
export const BOOKS_LOAD_SUCCESS = "BOOKS_LOAD_SUCCESS";
export const BOOKS_LOAD_FAILURE = "BOOKS_LOAD_FAILURE";
export const ADD_BOOK_TO_CART = "ADD_BOOK_TO_CART";
export const REMOVE_BOOK_FROM_CART = "REMOVE_BOOK_FROM_CART";
export const REMOVE_ALL_BOOKS_FROM_CART = "REMOVE_ALL_BOOKS_FROM_CART";
